name: Slack Mainline
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Start CD (AppStore) workflow
        uses: innocarpe/actions-slack@v1
        with:
          status: success
          success_text: '<!subteam^S6RFV3BFW> @${{ github.actor }} ë‹˜ì´ `${{ github.ref }}` ì˜ ì•±ìŠ¤í† ì–´ ë°°í¬ Action ì„ ì‹œì‘í–ˆìŠµë‹ˆë‹¤ ğŸš€'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: TestFlight Distribution Finished
        uses: innocarpe/actions-slack@v1
        with:
          status: success
          success_text: '<!subteam^S6RFV3BFW> TestFlight ë°°í¬ ì™„ë£Œ ğŸ’¯'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: TestFlight Distribution Failed
        uses: innocarpe/actions-slack@v1
        with:
          status: failure
          failure_text: <!subteam^S6RFV3BFW> TestFlight ë°°í¬ ì‹¤íŒ¨ ğŸ˜±
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: TestFlight Distribution Cancelled
        uses: innocarpe/actions-slack@v1
        with:
          status: cancelled
          cancelled_text: <!subteam^S6RFV3BFW> @${{ github.actor }} ë‹˜ì´ ì•±ìŠ¤í† ì–´ ì œì¶œì„ ì·¨ì†Œí–ˆìŠµë‹ˆë‹¤ âš ï¸
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: AppStore Submit Finished
        uses: innocarpe/actions-slack@v1
        with:
          status: success
          success_text: '<!subteam^S6RFV3BFW> ì•±ìŠ¤í† ì–´ ì œì¶œ ì™„ë£Œ âœ…'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: AppStore Submit Failed
        uses: innocarpe/actions-slack@v1
        with:
          status: failure
          failure_text: '<!subteam^S6RFV3BFW> ì•±ìŠ¤í† ì–´ ì œì¶œ ì‹¤íŒ¨ ğŸ˜±'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: AppStore Submit Cancelled
        uses: innocarpe/actions-slack@v1
        with:
          status: cancelled
          cancelled_text: <!subteam^S6RFV3BFW> @${{ github.actor }} ë‹˜ì´ ì•±ìŠ¤í† ì–´ ì œì¶œì„ ì·¨ì†Œí–ˆìŠµë‹ˆë‹¤ âš ï¸
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}